#property strict
#property version   "1.00"
#property description "RSI EA for XAUUSD H1 with risk controls and trade management"
#property copyright "Generated by AI"

#include <Trade/Trade.mqh>

input string         InpSymbol                  = "XAUUSD";
input ENUM_TIMEFRAMES InpTimeframe              = PERIOD_H1;
input int            InpRSIPeriod               = 14;
input double         InpBuyLevel                = 30.0;
input double         InpSellLevel               = 70.0;
input double         InpLotSize                 = 0.01;
input int            InpStopLossPoints          = 30;
input int            InpTakeProfitPoints        = 600;
input int            InpMaxTradesPerDay         = 1;
input double         InpMaxDrawdownPercent      = 5.0;
input int            InpMaxConsecutiveLosses    = 3;
input int            InpTrailingStopPoints      = 100;
input int            InpSlippagePoints         = 30;
input ulong          InpMagicNumber             = 20260101;

CTrade trade;
int rsi_handle = INVALID_HANDLE;
datetime last_bar_time = 0;

int trades_today = 0;
int consecutive_losses = 0;
double day_start_equity = 0.0;
int day_of_year_cache = -1;

bool IsNewBar()
{
   datetime t = iTime(InpSymbol, InpTimeframe, 0);
   if(t == 0) return false;
   if(t != last_bar_time)
   {
      last_bar_time = t;
      return true;
   }
   return false;
}

int DayOfYear(datetime time_value)
{
   MqlDateTime dt;
   TimeToStruct(time_value, dt);
   return dt.day_of_year;
}

void ResetDailyStatsIfNeeded()
{
   int doy = DayOfYear(TimeCurrent());
   if(doy != day_of_year_cache)
   {
      day_of_year_cache = doy;
      trades_today = 0;
      day_start_equity = AccountInfoDouble(ACCOUNT_EQUITY);
   }
}

bool IsTradeAllowedByRisk()
{
   if(day_start_equity <= 0.0)
      day_start_equity = AccountInfoDouble(ACCOUNT_EQUITY);

   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   double dd_percent = 0.0;
   if(day_start_equity > 0.0)
      dd_percent = (day_start_equity - equity) / day_start_equity * 100.0;

   if(dd_percent >= InpMaxDrawdownPercent)
      return false;

   if(trades_today >= InpMaxTradesPerDay)
      return false;

   if(consecutive_losses >= InpMaxConsecutiveLosses)
      return false;

   return true;
}

bool HaveOpenPosition()
{
   if(!PositionSelect(InpSymbol))
      return false;

   long magic = (long)PositionGetInteger(POSITION_MAGIC);
   if((ulong)magic != InpMagicNumber)
      return false;

   return true;
}

void ManageTrailingStop()
{
   if(!PositionSelect(InpSymbol))
      return;

   long magic = (long)PositionGetInteger(POSITION_MAGIC);
   if((ulong)magic != InpMagicNumber)
      return;

   ENUM_POSITION_TYPE type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
   double point = SymbolInfoDouble(InpSymbol, SYMBOL_POINT);
   int digits = (int)SymbolInfoInteger(InpSymbol, SYMBOL_DIGITS);
   double bid = SymbolInfoDouble(InpSymbol, SYMBOL_BID);
   double ask = SymbolInfoDouble(InpSymbol, SYMBOL_ASK);

   double sl = PositionGetDouble(POSITION_SL);
   double tp = PositionGetDouble(POSITION_TP);

   if(InpTrailingStopPoints <= 0)
      return;

   if(type == POSITION_TYPE_BUY)
   {
      double new_sl = bid - InpTrailingStopPoints * point;
      if(sl == 0.0 || new_sl > sl)
      {
         new_sl = NormalizeDouble(new_sl, digits);
         trade.PositionModify(InpSymbol, new_sl, tp);
      }
   }
   else if(type == POSITION_TYPE_SELL)
   {
      double new_sl = ask + InpTrailingStopPoints * point;
      if(sl == 0.0 || new_sl < sl)
      {
         new_sl = NormalizeDouble(new_sl, digits);
         trade.PositionModify(InpSymbol, new_sl, tp);
      }
   }
}

void UpdateConsecutiveLossesFromHistory()
{
   datetime from = TimeCurrent() - 86400 * 30;
   datetime to = TimeCurrent();
   if(!HistorySelect(from, to))
      return;

   int total = HistoryDealsTotal();
   int loss_count = 0;
   int win_count = 0;

   for(int i = total - 1; i >= 0; i--)
   {
      ulong deal_ticket = HistoryDealGetTicket(i);
      if(deal_ticket == 0)
         continue;

      string sym = HistoryDealGetString(deal_ticket, DEAL_SYMBOL);
      if(sym != InpSymbol)
         continue;

      long magic = HistoryDealGetInteger(deal_ticket, DEAL_MAGIC);
      if((ulong)magic != InpMagicNumber)
         continue;

      long entry_type = HistoryDealGetInteger(deal_ticket, DEAL_ENTRY);
      if(entry_type != DEAL_ENTRY_OUT)
         continue;

      double profit = HistoryDealGetDouble(deal_ticket, DEAL_PROFIT) +
                      HistoryDealGetDouble(deal_ticket, DEAL_SWAP) +
                      HistoryDealGetDouble(deal_ticket, DEAL_COMMISSION);

      if(profit < 0.0)
         loss_count++;
      else if(profit > 0.0)
         win_count++;
   }

   if(loss_count > 0 && win_count == 0)
      consecutive_losses = loss_count;
}

bool OpenBuy()
{
   double point = SymbolInfoDouble(InpSymbol, SYMBOL_POINT);
   int digits = (int)SymbolInfoInteger(InpSymbol, SYMBOL_DIGITS);
   double ask = SymbolInfoDouble(InpSymbol, SYMBOL_ASK);

   double sl = 0.0;
   double tp = 0.0;

   if(InpStopLossPoints > 0)
      sl = NormalizeDouble(ask - InpStopLossPoints * point, digits);
   if(InpTakeProfitPoints > 0)
      tp = NormalizeDouble(ask + InpTakeProfitPoints * point, digits);

   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippagePoints);
   trade.SetTypeFillingBySymbol(InpSymbol);

   return trade.Buy(InpLotSize, InpSymbol, 0.0, sl, tp, "RSI Buy");
}

void CheckExitAndEntry()
{
   if(Bars(InpSymbol, InpTimeframe) < InpRSIPeriod + 10)
      return;

   double rsi_buffer[];
   ArraySetAsSeries(rsi_buffer, true);

   if(CopyBuffer(rsi_handle, 0, 0, 3, rsi_buffer) < 3)
      return;

   double rsi_current = rsi_buffer[0];

   if(HaveOpenPosition())
   {
      if(rsi_current > InpSellLevel)
      {
         trade.PositionClose(InpSymbol);
      }
      return;
   }

   if(!IsTradeAllowedByRisk())
      return;

   if(rsi_current < InpBuyLevel)
   {
      if(OpenBuy())
      {
         trades_today++;
      }
   }
}

int OnInit()
{
   if(!SymbolSelect(InpSymbol, true))
      return INIT_FAILED;

   if(InpStopLossPoints <= 0 || InpTakeProfitPoints <= 0 || InpMaxTradesPerDay <= 0)
      return INIT_FAILED;

   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippagePoints);

   rsi_handle = iRSI(InpSymbol, InpTimeframe, InpRSIPeriod, PRICE_CLOSE);
   if(rsi_handle == INVALID_HANDLE)
      return INIT_FAILED;

   day_of_year_cache = DayOfYear(TimeCurrent());
   day_start_equity = AccountInfoDouble(ACCOUNT_EQUITY);
   UpdateConsecutiveLossesFromHistory();

   return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
   if(rsi_handle != INVALID_HANDLE)
   {
      IndicatorRelease(rsi_handle);
      rsi_handle = INVALID_HANDLE;
   }
}

void OnTick()
{
   ResetDailyStatsIfNeeded();
   ManageTrailingStop();

   if(!IsNewBar())
      return;

   CheckExitAndEntry();
}