#property copyright "Generated by AI"
#property link      ""
#property version   "1.00"
#property strict
#property description "RSI-based EA for XAUUSD on H1"

#include <Trade/Trade.mqh>

input string         InpSymbol                = "XAUUSD";
input ENUM_TIMEFRAMES InpTimeframe             = PERIOD_H1;
input int            InpRSIPeriod              = 14;
input double         InpRSIBuyLevel            = 30.0;
input double         InpRSICloseLevel          = 70.0;
input double         InpLotSize                = 0.01;
input int            InpStopLossPoints         = 1000;
input int            InpTakeProfitPoints       = 10000;
input int            InpMaxTradesPerDay        = 1;
input ulong          InpMagicNumber            = 0b6edaa0;
input int            InpDeviationPoints        = 10;

CTrade trade;
int rsi_handle = INVALID_HANDLE;
datetime last_bar_time = 0;

int trades_today = 0;
int day_of_year_cached = -1;

bool IsNewBar()
{
   datetime current_bar_time = iTime(InpSymbol, InpTimeframe, 0);
   if(current_bar_time == 0)
      return false;

   if(current_bar_time != last_bar_time)
   {
      last_bar_time = current_bar_time;
      return true;
   }
   return false;
}

void UpdateDailyCounter()
{
   MqlDateTime dt;
   TimeToStruct(TimeCurrent(), dt);

   if(day_of_year_cached != dt.day_of_year)
   {
      day_of_year_cached = dt.day_of_year;
      trades_today = 0;
   }
}

int CountOpenPositionsBySymbolMagic(const string symbol, const ulong magic)
{
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0)
         continue;

      if(PositionSelectByTicket(ticket))
      {
         string psym = PositionGetString(POSITION_SYMBOL);
         ulong pmagic = (ulong)PositionGetInteger(POSITION_MAGIC);
         if(psym == symbol && pmagic == magic)
            count++;
      }
   }
   return count;
}

bool ClosePositionsBySymbolMagic(const string symbol, const ulong magic)
{
   bool result = true;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0)
         continue;

      if(PositionSelectByTicket(ticket))
      {
         string psym = PositionGetString(POSITION_SYMBOL);
         ulong pmagic = (ulong)PositionGetInteger(POSITION_MAGIC);
         if(psym == symbol && pmagic == magic)
         {
            if(!trade.PositionClose(ticket))
               result = false;
         }
      }
   }
   return result;
}

bool GetRSIValue(double &rsi_current, double &rsi_previous)
{
   if(rsi_handle == INVALID_HANDLE)
      return false;

   double buffer[2];
   ArraySetAsSeries(buffer, true);

   if(CopyBuffer(rsi_handle, 0, 0, 2, buffer) < 2)
      return false;

   rsi_current = buffer[0];
   rsi_previous = buffer[1];
   return true;
}

double NormalizeVolume(double lots)
{
   double min_lot = SymbolInfoDouble(InpSymbol, SYMBOL_VOLUME_MIN);
   double max_lot = SymbolInfoDouble(InpSymbol, SYMBOL_VOLUME_MAX);
   double lot_step = SymbolInfoDouble(InpSymbol, SYMBOL_VOLUME_STEP);

   if(lots < min_lot)
      lots = min_lot;
   if(lots > max_lot)
      lots = max_lot;

   int steps = (int)MathRound(lots / lot_step);
   double normalized = steps * lot_step;

   return NormalizeDouble(normalized, 2);
}

bool OpenBuy()
{
   double ask = SymbolInfoDouble(InpSymbol, SYMBOL_ASK);
   if(ask <= 0.0)
      return false;

   double sl = 0.0;
   double tp = 0.0;

   if(InpStopLossPoints > 0)
      sl = ask - InpStopLossPoints * _Point;
   if(InpTakeProfitPoints > 0)
      tp = ask + InpTakeProfitPoints * _Point;

   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpDeviationPoints);

   double volume = NormalizeVolume(InpLotSize);

   return trade.Buy(volume, InpSymbol, ask, sl, tp, "RSI BUY");
}

int OnInit()
{
   if(!SymbolSelect(InpSymbol, true))
      return INIT_FAILED;

   rsi_handle = iRSI(InpSymbol, InpTimeframe, InpRSIPeriod, PRICE_CLOSE);
   if(rsi_handle == INVALID_HANDLE)
      return INIT_FAILED;

   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpDeviationPoints);

   last_bar_time = iTime(InpSymbol, InpTimeframe, 0);
   UpdateDailyCounter();

   return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
   if(rsi_handle != INVALID_HANDLE)
   {
      IndicatorRelease(rsi_handle);
      rsi_handle = INVALID_HANDLE;
   }
}

void OnTick()
{
   if(_Symbol != InpSymbol)
   {
      // EA can still operate on the configured symbol even if attached elsewhere.
   }

   UpdateDailyCounter();

   double rsi_current = 0.0, rsi_previous = 0.0;
   if(!GetRSIValue(rsi_current, rsi_previous))
      return;

   int open_positions = CountOpenPositionsBySymbolMagic(InpSymbol, InpMagicNumber);

   // Exit logic: close BUY positions when RSI is above the exit threshold.
   if(open_positions > 0)
   {
      if(rsi_current > InpRSICloseLevel)
         ClosePositionsBySymbolMagic(InpSymbol, InpMagicNumber);

      return;
   }

   // Entry logic: open BUY when RSI is below the buy threshold.
   if(trades_today >= InpMaxTradesPerDay)
      return;

   if(rsi_current < InpRSIBuyLevel)
   {
      if(OpenBuy())
         trades_today++;
   }
}